### ISSUE TITLE
Containers using stargz images experience issues after restarting stargz-snapshotter.service

### ISSUE THREAD

**Issue by whygyc** [containerd/stargz-snapshotter#1520]
Hello, I'm conducting an experiment using `Containerd+stargz`. It was working well until I restarted the `stargz-snapshotter.service` (systemctl restart stargz-snapshotter.service).
When attempting to enter the container (`nerdctl exec -it e0bc bash`), I received the following error, which was resolved after restarting the container:
```
# nerdctl exec -it e0bc bash
FATA[0000] OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: process_linux.go:170: writing config to pipe caused: write init-p: broken pipe: unknown
```
I noticed that the stargz image seems to be pulled again, even though it had already been fully pulled and cached in `/var/lib/containerd-stargz-grpc/stargz/` before the restart. 
Additionally, there were issues with the layer in `/var/lib/containerd-stargz-grpc/snapshotter/snapshots/` when the `stargz-snapshotter.service` stops.

My questions are:
1. After restarting the `stargz-snapshotter.service`, all containers launched with stargz images experience this issue. Is there a way to avoid this? Is this because of the limitations of using CRFS?
2. Is it possible to detach the stargz image from the `stargz-snapshotter.service` once it has been fully pulled to the local machine, in order to avoid service disruptions?

This does not seem suitable for production environments.
Please let me know if I missed anything. Thank you.

**Comment by ktock** [comment]
As of now, all containers launched with stargz-snapshotter (`containerd-stargz-grpc`) needs to be killed before restarting the snapshotter and they needs to be re-deployed after the snapshotter restarts. This is because currently stargz-snapshotter(`containerd-stargz-grpc`) process works as a FUSE server for coantainer's rootfs on the node.

> I noticed that the stargz image seems to be pulled again

stargz-snapshotter tries to reuse cached contents but they have TTL as configured by [`resolve_result_entry_ttl_sec`(int)](https://github.com/containerd/stargz-snapshotter/blob/94b12086ace4119e86d2db0d6343d7c734b56671/fs/config/config.go#L41) in the config file. Increasing this value might allow reusing the layers later. In the future, if needed, we can add features to manually manage cached layers without TTL.

> Is it possible to detach the stargz image from the stargz-snapshotter.service once it has been fully pulled to the local machine, in order to avoid service disruptions?

Detaching FUSE server is unsupported as of now. But SGTM about adding such features.
