### ISSUE TITLE
optimzations for ctr-remote optimize

### ISSUE THREAD

**Issue by strigazi** [containerd/stargz-snapshotter#169]
Hello,

I would discuss some improvements we could do in ctr-remote image optimize.
 
* While optimizing an image with a very large number of files, we noticed that
  the snapshotter used a single core at 100%. Could we parallelize (map reduce?)
  to all cores?
* Allow ctr-remote image optimize based on optimized images. We could use as
  base image an already optimized image, use all stargzified layers in the registry,
  recreate only the layer with the location of the files, push only the new layers,
* Mount data and allow netwok access duting optimize. To optimize based on a
  type of workload, we could use some data based on that workload. i.e. mount
  a dateset to run a task in the container.

Cheers,
Spyros

**Comment by ktock** [comment]
@strigazi Thanks for the proposals! I totally agree with.
The following is my thought about the feasibility of these features.

> While optimizing an image with a very large number of files, we noticed that
> the snapshotter used a single core at 100%. Could we parallelize (map reduce?)
> to all cores?

I think it's possible to parallelize constructing stargz blob (= [compressing and concatinating file entries and appending TOC JSON at the tail](https://github.com/containerd/stargz-snapshotter/blob/master/docs/stargz-estargz.md)) because stargz/eStargz is just tar.gz and the order of entries [is determined before this construction phase](https://github.com/containerd/stargz-snapshotter/blob/3a04e4c2c116c85b4b66d01945cf7ebcb7a2eb5a/cmd/ctr-remote/commands/optimize.go#L337-L340).

The idea is that we can divide the stargz construction into several (maybe num of cores) goroutine jobs then we can acquire sub-stargz blobs from them. Then we concatenate these sub blobs (but TOC JSON of each sub blobs shouldn't be included here). Finally, we merge TOC JSONs of these sub-stargz blobs into one with recalculating [`TOCEntry.Offset`](https://github.com/google/crfs/blob/71d77da419c90be7b05d12e59945ac7a8c94a543/stargz/stargz.go#L154-L159) (the offset to each entry) then append it to the tail of the result stargz blob.

>  Allow ctr-remote image optimize based on optimized images. We could use as
> base image an already optimized image, use all stargzified layers in the registry,
> recreate only the layer with the location of the files, push only the new layers,

I agree with that. We can add a flag for enabling/disabling this feature. For already optimized layers, we just need to copy it from the source to the destination repo (of course, if they already exist in the dest repo or can be [cross-repo mounted](https://docs.docker.com/registry/spec/api/#cross-repository-blob-mount), we don't need to copy them).

Further possible improvement is mounting (lazy pulling) already optimized (stargz/eStargz) layers from the source repo when preparing the sandbox environment for profiling file accesses. This will also help to reduce the time to take for the optimization.

> Mount data and allow netwok access duting optimize. To optimize based on a
> type of workload, we could use some data based on that workload. i.e. mount
> a dateset to run a task in the container.

Currently, the sandbox environment for profiling file accesses is created using runc. We can add mount functionality to it by [configuring runc](https://github.com/containerd/stargz-snapshotter/blob/3a04e4c2c116c85b4b66d01945cf7ebcb7a2eb5a/cmd/ctr-remote/sampler/sampler.go#L45-L48) to do so. Adding networking feature will require an additional logic for configuring network interface in that sandbox (e.g. using [CNI plugins](https://github.com/containernetworking/plugins))

Another option for achieving this is simply to use containerd instead of runc. This might be easier than directly configuring runc and CNI plugins.

**Comment by ktock** [comment]
@strigazi Most of issues mentioned here seem to be solved through #171 #172 #173 #174.  Could you tell us if there are still something missing?

**Comment by strigazi** [comment]
@ktock They look great!
