### ISSUE TITLE
image request: wordpress and mariadb (for Compose demo)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/stargz-snapshotter#298]
nerdctl will support Compose soon: https://github.com/containerd/nerdctl/pull/156

Can we get pre-converted esgz images of `wordpress:5.7` and `mariadb:10.5` for demo of Compose with stargz?

**Comment by AkihiroSuda** [comment]
(I'm not sticking to wordpress, let me know if there is a better demo application for Compose)

**Comment by ktock** [comment]
Do you have any preference about the workload (or command execution) to be optimized for?

e.g. https://github.com/containerd/stargz-snapshotter/blob/ca3ed2eaba06a750a8f9d05624cbbda25a935aad/script/benchmark/hello-bench/src/hello.py#L91-L117

(I'm not a Java expert but Java-based web apps might be other good demo candidates because they tend to be big images)

**Comment by AkihiroSuda** [comment]
Just running mysqld --version and php --version would be fine for preloading the binaries
