### ISSUE TITLE
Question around stargz's overlayfs implementation as fallback snapshotter.

### ISSUE THREAD

**Issue by alakesh** [containerd/stargz-snapshotter#425]
Stargz snapshotter seems to have implementation for overlayfs snapshotter intended for fallback if image is not estargz. I see some common code between stargz and containerd's overlayfs. This is probably to support overlayfs as fallback snapshotter. 

https://github.com/containerd/containerd/tree/main/snapshots/overlay/overlay.go
https://github.com/containerd/stargz-snapshotter/tree/main/snapshot/snapshot.go

Given the implementations are very similar, is it safe to assume that having stargz as default snapshotter for non-stargz images as well, does not introduce any performance degradation? Is the fallback implementation intended to support non stargz images at large scale? Any comments or experience around this would be appreciated.

Also, trying to understand why stargz cannot use overlafs as a module, instead of coming up with a parallel implementation.

**Comment by ktock** [comment]
> Stargz snapshotter seems to have implementation for overlayfs snapshotter intended for fallback if image is not estargz. I see some common code between stargz and containerd's overlayfs. This is probably to support overlayfs as fallback snapshotter.

Yes, stargz snapshotter fallbacks to overlayfs if the pulling image isn't stargz/estargz.

> Given the implementations are very similar, is it safe to assume that having stargz as default snapshotter for non-stargz images as well, does not introduce any performance degradation? Is the fallback implementation intended to support non stargz images at large scale? Any comments or experience around this would be appreciated.

Overlayfs mode of stargz snapshotter is identical to overlayfs snaphsotter so you can use stargz snapshotter for non-stargz images as well.

> Also, trying to understand why stargz cannot use overlafs as a module, instead of coming up with a parallel implementation.

In the future, we would like to see containerd overlayfs snapshotter supports configuring additional mounts so that we can use it as a module with configuring it for stargz/estargz FUSE mount.

**Comment by ktock** [comment]
@alakesh [Our snapshotter](https://github.com/containerd/stargz-snapshotter/blob/189160caceb0a1c5fe25f5e929face62ec33c60a/snapshot/snapshot.go) is identical to containerd's overlayfs snapshotter except it accepts [`FileSystem` interface](https://github.com/containerd/stargz-snapshotter/blob/189160caceb0a1c5fe25f5e929face62ec33c60a/snapshot/snapshot.go#L68-L72) so that it can use mountpoints for snapshots. Our [`fs` package](https://github.com/containerd/stargz-snapshotter/tree/189160caceb0a1c5fe25f5e929face62ec33c60a/fs) is an implementation of `FileSystem` interface that provides mountpoints of stargz/estargz.
It would be great if containerd's overlayfs snapshotter accepts `FileSystem` and if it handles mountpoints provided from that interface because we can use that (configurable) overlayfs snapshotter with our stargz/estargz `FileSystem` implementation, instead of having forked overlayfs snapshotter.
