### ISSUE TITLE
fuse mount /var/lib/stargz-store/store has no read write

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containerd/stargz-snapshotter#540]
Hi,

I try to follow the installation procedure for podman found here https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md on a RHEL 8.5 machine (x64). I did install fuse and didn't tailor anything (that I know of), using v0.10.1.

In the end, here are the rights I have in /var/lib/stargz-store:

```
[root@ncelabjkslvrg01 stargz]# ls -la /var/lib/stargz-store/
total 12
drwxr-xr-x   4 root root 4096 Nov 25 15:24 .
drwxr-xr-x. 41 root root 4096 Nov 25 15:24 ..
drwx------   2 root root 4096 Nov 25 15:24 pool
d---------   0 root root    0 Jan  1  1970 store
```

which seems weird, and indeed, when running podman (as root), it doesn't seem to be happy:

```
[root@ncelabjkslvrg01 stargz]# podman run -t -i --rm stargz/node:13.13.0-esgz
Error: overlay: can't stat imageStore dir /var/lib/stargz-store/store:ref: stat /var/lib/stargz-store/store:ref: no such file or directory
```

Why do I have no read/write in "store" ? Should I configure something in a special way ?

Cheers,
Romain

**Comment by ktock** [comment]
It seems that the error comes from [additional**image**store](https://github.com/containers/storage/blob/b1f1ca77147adec41b7f6346f15fc4889cdd9f98/drivers/overlay/overlay.go#L444-L463) configuration but not from additional**layer**store needed for lazy pulling. Please configure additional**layer**store as described in https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md 

And please use images on `ghcr.io/stargz-containers` instead of `docker.io/stargz`, as described in https://github.com/containerd/stargz-snapshotter/blob/main/docs/pre-converted-images.md.

**Comment by Romain-Geissler-1A** [comment]
Ah, I feel dumb right now !

Indeed you are right, it works with additional**layer**stores (with an "s" at the end). I didn't copy/paste the full line from the installation page, only the value, as by default podman configuration files comes with an empty additionalimagestores array, and I read it too quickly.

Thanks for the support, and really sorry for not strictly following the installation procedure !
