### ISSUE TITLE
Integrate with dragonfly

### ISSUE THREAD

**Issue by sequix** [containerd/stargz-snapshotter#92]
I am trying to integrate this project with P2P to speed up container boot up even more. I tried uber/kraken, but it is too heavy, so many component. So I turned into dragonflyoss/dragonfly, which works.

My question is will HTTP range still works behind a registry mirror, like dragonfly's dfclient?

Maybe I can @lowzj, one of dragonfly developers, who starred this repo?

**Comment by ktock** [comment]
Yes, HTTP range request should work behind registry mirrors as long as they support [Docker](https://docs.docker.com/registry/spec/api/)/[OCI](https://github.com/opencontainers/distribution-spec)-compatible registry API. You can add the registry mirror configuration to this snapshotter like the following:
```toml
[[resolver.host."exampleregistry.io".mirrors]]
host = "mirrorhost.io"
```
The [config toml file](https://github.com/containerd/stargz-snapshotter/blob/28af649b55ac39efc547b2e7f14f81a33a8212e1/Dockerfile#L38) can be passed to the snapshotter [with `--config` option](https://github.com/containerd/stargz-snapshotter/blob/28af649b55ac39efc547b2e7f14f81a33a8212e1/script/pullsecrets/config/stargz-snapshotter.service#L8).

**Comment by sequix** [comment]
It is work, closed.

**Comment by ktock** [comment]
@sequix Thanks for trying this. Did you see any performance improvements by this integration?

**Comment by sequix** [comment]
![image](https://user-images.githubusercontent.com/15651400/81884388-5c23bd80-95ca-11ea-8284-3c40fbc60417.png)

Well, I did not test this much, but it dose have some improvements. This is a 359MiB image with 100M bandwidth, the first time took 8s to mount, and the second time stargz-snapshotter fetched data from dragonfly's cache (which residents in the same cluster, maybe not same node) to mount fs at another node with 5s.

**Comment by ktock** [comment]
Interesting. Time to take for prefetching and background fetching possibly speeded up by the dragonfly's cache.
But the time to take for *mount* shouldn't be affected by them because they are [held in the background (in goroutines)](https://github.com/containerd/stargz-snapshotter/blob/fff955fd009160587b255408b83c174c4d00ded5/stargz/fs.go#L238-L281). The improvement might be because the RTT for [some requests (authn, pinging and getting size) during layer resolution](https://github.com/containerd/stargz-snapshotter/blob/fff955fd009160587b255408b83c174c4d00ded5/stargz/remote/resolver.go#L186-L200) got shorter, or the time to take for fetching image manifests got shorter?

Either way, we seem to need more investigation.
